#!/usr/bin/env bash
# hotel-e2e.sh — hotel end-to-end smoke test.
#
# The CSL orchestrated hotel flow is:
#
#   hotel-search → get-hotel-avail → get-hotel-details → hotel-price-check
#     → create-booking (hotel) → get-booking → cancel-booking
#
# This library currently wraps:
#
#   * hotel-search      — property discovery (no rates)
#   * get-hotel-content — descriptive + media content for a single property
#                         (no rates; runs off the hotel code from step 1)
#   * get-hotel-avail   — lead rates, produces rateKeys
#   * get-hotel-details — per-property rate grid + descriptive content
#                         (canonical "Refine" step between Avail and Price Check)
#   * hotel-price-check — revalidates a rateKey, produces bookingKey
#
# The `get-hotel-rate-info` service is also wrapped but intentionally not
# exercised here — it's off the orchestrated booking path and currently
# returns empty-`Complete` envelopes from CERT (see PR #83 for the
# precise reproducer). Test it directly via the CLI when needed.
#
#   * book-hotel              — CreatePassengerNameRecord v2.5.0, hotel
#                               path. Consumes the bookingKey from
#                               price-check, produces a Sabre PNR locator.
#   * get-booking             — booking-management v1 getBooking. Verified
#                               in CERT 2026-07-07 against a CSL-segment
#                               hotel PNR — returns hotels[] with room,
#                               rate, and payment detail. Previously
#                               returned UNAUTHORIZED_ACCESS on this EPR;
#                               that entitlement gap is now resolved (see
#                               docs/guides/hotel-booking-flow.md).
#   * cancel-booking          — booking-management v1 cancelBooking.
#                               Verified in CERT 2026-05-07 against a
#                               CSL-segment hotel PNR. Contradicts Sabre's
#                               CSL Setup & Guides page which lists
#                               "Get Reservation — SOAP only" at step 5.
#
# ## What this script does today
#
#   Step 1: hotel-search      — runs against Sabre CERT, picks the first hotel
#   Step 2: get-hotel-content — runs against Sabre CERT using the hotel code
#                               from step 1, surfaces amenity / description /
#                               media counts so descriptive + media content
#                               is visible
#   Step 3: get-hotel-avail   — runs against Sabre CERT, extracts a rateKey
#                               from the first hotel's ConvertedRateInfo
#                               (or falls back to RateInfo)
#   Step 4: get-hotel-details — runs against Sabre CERT using the rateKey
#                               from step 3, surfaces room count + rate-plan
#                               count so the rate grid is visible
#   Step 5: hotel-price-check — runs against Sabre CERT using the rateKey
#                               from step 3 (or a --rate-key override)
#   Step 6: book-hotel        — runs against Sabre CERT using the bookingKey
#                               from step 5.
#   Step 7: get-booking       — runs against Sabre CERT using the PNR
#                               locator from step 6, surfaces the hotel
#                               name and confirmation ID so the retrieved
#                               reservation is visible.
#   Step 8: cancel-booking    — runs against Sabre CERT with --cancel-all
#                               so the script self-cleans. Also invoked
#                               from the fail/exit trap if an earlier step
#                               died after the PNR was created.
#
# ## Prerequisites
#   1. `npm run build`
#   2. A .env file with SABRE_CLIENT_ID, SABRE_CLIENT_SECRET,
#      SABRE_BASE_URL (loaded automatically by the CLI). SABRE_PCC is
#      sourced explicitly by this script and forwarded to every step via
#      --pcc, because the CLI does not fall back to env.pcc on hotel
#      commands. Without a PCC, Sabre CSL routes rate-info requests
#      through a default that commonly returns empty envelopes.
#   3. `jq` on PATH.
#
# Step 6 uses Sabre's published CERT test card (4444333322221111) with
# a future expiry — not a real PAN. Hardcoded in the script because
# CERT test data does not need PCI treatment.
#
# Step 6 guest identity is generated by scripts/lib/random-person.sh;
# pass --seed to replay a prior run's identity.
#
# ## Usage
#   scripts/hotel-e2e.sh --ref-point 6:BWI:CODE --start-date 2026-06-20 --end-date 2026-06-22
#   scripts/hotel-e2e.sh --ref-point 6:BWI:CODE --rate-key '...opaque...'
#   scripts/hotel-e2e.sh --geo-code 32.758,-97.08 --radius 2
#   scripts/hotel-e2e.sh --seed 42         # reproduce a prior run's guest
#   scripts/hotel-e2e.sh --skip-cancel     # leave the PNR live in CERT
#
# ## Flags
#   --ref-point <T:V:C>            Anchor (default: 6:BWI:CODE)
#   --geo-code <lat,lon>           Alternative anchor
#   --address <fields>             Alternative anchor
#   --radius <n>                   Search radius (default: 5)
#   --uom <MI|KM>                  Unit of measure (default: MI)
#   --max-results <n>              Properties per page (default: 3)
#   --currency-code <ISO>          Currency for get-hotel-avail (default: USD)
#   --start-date <YYYY-MM-DD>      Stay start (default: 30 days out)
#   --end-date <YYYY-MM-DD>        Stay end   (default: start + 2 days)
#   --best-only <1-4>              get-hotel-avail BestOnly (default: 1)
#   --rate-key <key>               Skip step 3's key extraction and supply
#                                  a key directly to step 5.
#   --given-name <name>            Guest given name (default: randomly generated)
#   --surname <name>               Guest surname (default: randomly generated)
#   --phone <number>               Guest phone (default: randomly generated)
#   --email <addr>                 Guest email (default: randomly generated)
#   --seed <n>                     Reproduce a prior run's random identity
#   --skip-cancel                  Leave the PNR live (skip step 8)
#   --base-url <url>               Override SABRE_BASE_URL
#   -h, --help                     Show this help

set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib/random-person.sh
source "$SCRIPT_DIR/lib/random-person.sh"

CLI="node dist/cli.js"
REF_POINT="6:BWI:CODE"
GEO_CODE=""
ADDRESS=""
RADIUS="5"
UOM="MI"
MAX_RESULTS="3"
CURRENCY_CODE="USD"
START_DATE=""
END_DATE=""
BEST_ONLY="1"
RATE_KEY_OVERRIDE=""
GIVEN_NAME=""
SURNAME=""
PHONE=""
EMAIL=""
SEED=""
SKIP_CANCEL=0
BASE_URL=""

usage() {
  # Reproduces the header comment block. Update the line range when the
  # header grows or shrinks.
  sed -n '2,102p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref-point) REF_POINT="${2:-}"; GEO_CODE=""; ADDRESS=""; shift 2 ;;
    --geo-code) GEO_CODE="${2:-}"; REF_POINT=""; ADDRESS=""; shift 2 ;;
    --address) ADDRESS="${2:-}"; REF_POINT=""; GEO_CODE=""; shift 2 ;;
    --radius) RADIUS="${2:-}"; shift 2 ;;
    --uom) UOM="${2:-}"; shift 2 ;;
    --max-results) MAX_RESULTS="${2:-}"; shift 2 ;;
    --currency-code) CURRENCY_CODE="${2:-}"; shift 2 ;;
    --start-date) START_DATE="${2:-}"; shift 2 ;;
    --end-date) END_DATE="${2:-}"; shift 2 ;;
    --best-only) BEST_ONLY="${2:-}"; shift 2 ;;
    --rate-key) RATE_KEY_OVERRIDE="${2:-}"; shift 2 ;;
    --given-name) GIVEN_NAME="${2:-}"; shift 2 ;;
    --surname) SURNAME="${2:-}"; shift 2 ;;
    --phone) PHONE="${2:-}"; shift 2 ;;
    --email) EMAIL="${2:-}"; shift 2 ;;
    --seed) SEED="${2:-}"; shift 2 ;;
    --skip-cancel) SKIP_CANCEL=1; shift ;;
    --base-url) BASE_URL="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown argument '$1'" >&2; usage >&2; exit 2 ;;
  esac
done

generate_person "$SEED"
GIVEN_NAME="${GIVEN_NAME:-$PERSON_GIVEN_NAME}"
SURNAME="${SURNAME:-$PERSON_SURNAME}"
PHONE="${PHONE:-$PERSON_PHONE}"
EMAIL="${EMAIL:-$PERSON_EMAIL}"
echo "guest: $GIVEN_NAME $SURNAME  phone=$PHONE  email=$EMAIL  (seed=$PERSON_SEED)"

if ! command -v jq >/dev/null 2>&1; then
  echo "error: 'jq' is required on PATH" >&2
  exit 2
fi

if [[ ! -f "dist/cli.js" ]]; then
  echo "error: dist/cli.js not found — run 'npm run build' first" >&2
  exit 2
fi

# Source .env so we can read SABRE_PCC. The CLI already reads
# SABRE_CLIENT_ID / SABRE_CLIENT_SECRET / SABRE_BASE_URL itself, but the
# hotel commands do not fall back to env.pcc, so the script forwards PCC
# on every call that accepts it.
if [[ -f ".env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi

PCC_FLAG=()
if [[ -n "${SABRE_PCC:-}" ]]; then
  PCC_FLAG=(--pcc "$SABRE_PCC")
else
  echo "warning: SABRE_PCC not set — hotel steps will run without --pcc." >&2
  echo "         Sabre CSL typically returns empty envelopes without a PCC." >&2
fi

# Default stay window: 30 days from today, 2-night stay. macOS and GNU date
# differ on `-d` / `-v`; probe once at startup.
if [[ -z "$START_DATE" ]]; then
  if date -v+30d +%Y-%m-%d >/dev/null 2>&1; then
    START_DATE=$(date -v+30d +%Y-%m-%d)
    END_DATE=${END_DATE:-$(date -v+32d +%Y-%m-%d)}
  else
    START_DATE=$(date -d '+30 days' +%Y-%m-%d)
    END_DATE=${END_DATE:-$(date -d '+32 days' +%Y-%m-%d)}
  fi
fi
if [[ -z "$END_DATE" ]]; then
  echo "error: --end-date required when --start-date is supplied" >&2
  exit 2
fi

BASE_URL_FLAG=()
[[ -n "$BASE_URL" ]] && BASE_URL_FLAG=(--base-url "$BASE_URL")

TMP_ERR=$(mktemp)
SEARCH_FILE=$(mktemp)
CONTENT_FILE=$(mktemp)
AVAIL_FILE=$(mktemp)
DETAILS_FILE=$(mktemp)
PRICE_FILE=$(mktemp)
trap 'rm -f "$TMP_ERR" "$SEARCH_FILE" "$CONTENT_FILE" "$AVAIL_FILE" "$DETAILS_FILE" "$PRICE_FILE"' EXIT

run_cli() {
  : > "$TMP_ERR"
  "$@" 2>"$TMP_ERR"
}

PNR_LOCATOR=""
CLEANUP_ATTEMPTED=0

cleanup() {
  [[ -z "$PNR_LOCATOR" || "$CLEANUP_ATTEMPTED" == "1" ]] && return
  [[ "$SKIP_CANCEL" == "1" ]] && return
  CLEANUP_ATTEMPTED=1
  echo "" >&2
  echo "cleanup: attempting cancel-booking for $PNR_LOCATOR" >&2
  if $CLI cancel-booking "${BASE_URL_FLAG[@]}" \
      --confirmation-id "$PNR_LOCATOR" --cancel-all >/dev/null 2>&1; then
    echo "cleanup: cancel-booking succeeded" >&2
  else
    echo "cleanup: cancel-booking FAILED (manual cancellation may be required)" >&2
  fi
}

fail() {
  echo "" >&2
  echo "$1 FAILED" >&2
  cleanup
  exit 1
}

step() {
  local n="$1" label="$2"
  echo ""
  echo "[$n] $label"
  printf '%*s\n' $(( ${#n} + ${#label} + 4 )) '' | tr ' ' '-'
}

skip() {
  local n="$1" label="$2" reason="$3"
  echo ""
  echo "[$n] $label  (SKIPPED)"
  printf '%*s\n' $(( ${#n} + ${#label} + 14 )) '' | tr ' ' '-'
  echo "reason: $reason"
}

ANCHOR_FLAGS=()
if [[ -n "$REF_POINT" ]]; then
  ANCHOR_FLAGS=(--ref-point "$REF_POINT")
elif [[ -n "$GEO_CODE" ]]; then
  ANCHOR_FLAGS=(--geo-code "$GEO_CODE")
elif [[ -n "$ADDRESS" ]]; then
  ANCHOR_FLAGS=(--address "$ADDRESS")
fi

# ---------------------------------------------------------------------------
# Step 1 — hotel-search
# ---------------------------------------------------------------------------
step 1 "hotel-search"

if ! run_cli $CLI hotel-search "${BASE_URL_FLAG[@]}" "${PCC_FLAG[@]}" \
  "${ANCHOR_FLAGS[@]}" \
  --radius "$RADIUS" \
  --uom "$UOM" \
  --max-results "$MAX_RESULTS" \
  --format json >"$SEARCH_FILE"; then
  cat "$TMP_ERR" >&2
  fail "hotel-search"
fi

HOTEL_COUNT=$(jq '.hotels | length' "$SEARCH_FILE")
echo "Found $HOTEL_COUNT hotel(s):"
jq -r '.hotels[] | "  - \(.code)  \(.name // "(no name)")"' "$SEARCH_FILE"
(( HOTEL_COUNT == 0 )) && fail "hotel-search returned 0 properties"

CONTENT_HOTEL_CODE=$(jq -r '.hotels[0].code // empty' "$SEARCH_FILE")
CONTENT_CODE_CONTEXT=$(jq -r '.hotels[0].codeContext // empty' "$SEARCH_FILE")

# ---------------------------------------------------------------------------
# Step 2 — get-hotel-content
# ---------------------------------------------------------------------------
if [[ -z "$CONTENT_HOTEL_CODE" ]]; then
  skip 2 "get-hotel-content" "hotel-search returned no code to look up"
else
  step 2 "get-hotel-content ($CONTENT_HOTEL_CODE)"

  CONTENT_CODE_CONTEXT_FLAG=()
  [[ -n "$CONTENT_CODE_CONTEXT" ]] && CONTENT_CODE_CONTEXT_FLAG=(--code-context "$CONTENT_CODE_CONTEXT")

  if ! run_cli $CLI get-hotel-content "${BASE_URL_FLAG[@]}" \
    --hotel-code "$CONTENT_HOTEL_CODE" "${CONTENT_CODE_CONTEXT_FLAG[@]}" \
    --with-property-info --with-location --with-amenities --with-security \
    --with-media --media-images MEDIUM \
    --format json >"$CONTENT_FILE"; then
    cat "$TMP_ERR" >&2
    fail "get-hotel-content"
  fi

  CONTENT_NAME=$(jq -r '.hotel.info.hotelName // empty' "$CONTENT_FILE")
  CONTENT_AMENITY_COUNT=$(jq -r '(.hotel.descriptiveInfo.amenities // []) | length' "$CONTENT_FILE")
  CONTENT_MEDIA_COUNT=$(jq -r '(.hotel.mediaInfo.items // []) | length' "$CONTENT_FILE")
  if [[ -n "$CONTENT_NAME" ]]; then
    echo "content hotel:        $CONTENT_NAME"
    echo "content amenities:    $CONTENT_AMENITY_COUNT"
    echo "content media items:  $CONTENT_MEDIA_COUNT"
  else
    echo "no hotel returned (diagnostics-only envelope)"
    jq '.applicationResults // empty' "$CONTENT_FILE"
  fi
fi

# ---------------------------------------------------------------------------
# Step 3 — get-hotel-avail
# ---------------------------------------------------------------------------
RATE_KEY="$RATE_KEY_OVERRIDE"

if [[ -n "$RATE_KEY" ]]; then
  skip 3 "get-hotel-avail" "using --rate-key override from the command line"
else
  step 3 "get-hotel-avail ($START_DATE → $END_DATE in $CURRENCY_CODE)"

  if ! run_cli $CLI get-hotel-avail "${BASE_URL_FLAG[@]}" "${PCC_FLAG[@]}" \
    "${ANCHOR_FLAGS[@]}" \
    --radius "$RADIUS" \
    --uom "$UOM" \
    --currency-code "$CURRENCY_CODE" \
    --start-date "$START_DATE" \
    --end-date "$END_DATE" \
    --best-only "$BEST_ONLY" \
    --max-results "$MAX_RESULTS" \
    --format json >"$AVAIL_FILE"; then
    cat "$TMP_ERR" >&2
    fail "get-hotel-avail"
  fi

  AVAIL_HOTEL_COUNT=$(jq '.hotels | length' "$AVAIL_FILE")
  echo "Avail returned $AVAIL_HOTEL_COUNT hotel(s)."

  # Pull the first rateKey we can find, preferring ConvertedRateInfo (which
  # the OAS marks rateKey required). Fall back to RateInfo. Also scan rate
  # plans inside rooms in case the top-level rate lists were empty.
  RATE_KEY=$(jq -r '
    (.hotels[]? | (
      .rateInfo.convertedRateInfo[]?.rateKey,
      .rateInfo.rateInfo[]?.rateKey,
      .rateInfo.rooms[]?.ratePlans[]?.rateKey
    )) // empty
    | select(. != null and . != "")
  ' "$AVAIL_FILE" | head -n 1)

  if [[ -z "$RATE_KEY" ]]; then
    # Still useful to surface any diagnostics Sabre returned.
    jq '.applicationResults // empty' "$AVAIL_FILE"
    fail "get-hotel-avail returned no rateKey"
  fi
  echo "rateKey (first):  ${RATE_KEY:0:64}..."
fi

# ---------------------------------------------------------------------------
# Step 4 — get-hotel-details
# ---------------------------------------------------------------------------
step 4 "get-hotel-details"

if ! run_cli $CLI get-hotel-details "${BASE_URL_FLAG[@]}" "${PCC_FLAG[@]}" \
  --rate-key "$RATE_KEY" \
  --with-property-info \
  --with-location \
  --with-amenities \
  --format json >"$DETAILS_FILE"; then
  cat "$TMP_ERR" >&2
  fail "get-hotel-details"
fi

DETAILS_HOTEL=$(jq -r '.hotel.info.code // empty' "$DETAILS_FILE")
DETAILS_ROOM_COUNT=$(jq -r '(.hotel.rooms // []) | length' "$DETAILS_FILE")
DETAILS_RATE_PLAN_COUNT=$(jq -r '
  [(.hotel.rooms // [])[]?.ratePlans | length] | add // 0
' "$DETAILS_FILE")
DETAILS_HAS_DESCRIPTIVE=$(jq -r '
  if .hotel.descriptiveInfo != null then "yes" else "no" end
' "$DETAILS_FILE")
if [[ -n "$DETAILS_HOTEL" ]]; then
  echo "details hotel:        $DETAILS_HOTEL"
  echo "details room count:   $DETAILS_ROOM_COUNT"
  echo "details rate plans:   $DETAILS_RATE_PLAN_COUNT"
  echo "details descriptive:  $DETAILS_HAS_DESCRIPTIVE"
else
  echo "no hotel returned (diagnostics-only envelope)"
  jq '.applicationResults // empty' "$DETAILS_FILE"
fi

# ---------------------------------------------------------------------------
# Step 5 — hotel-price-check
# ---------------------------------------------------------------------------
step 5 "hotel-price-check"

if ! run_cli $CLI hotel-price-check "${BASE_URL_FLAG[@]}" "${PCC_FLAG[@]}" \
  --rate-key "$RATE_KEY" \
  --start-date "$START_DATE" \
  --end-date "$END_DATE" \
  --format json >"$PRICE_FILE"; then
  cat "$TMP_ERR" >&2
  fail "hotel-price-check"
fi

BOOKING_KEY=$(jq -r '.bookingKey // empty' "$PRICE_FILE")
PRICE_CHANGE=$(jq -r '.priceChange // empty' "$PRICE_FILE")
WARNINGS=$(jq -r '.applicationResults.warnings // [] | length' "$PRICE_FILE")
ERRORS=$(jq -r '.applicationResults.errors // [] | length' "$PRICE_FILE")

if [[ -n "$BOOKING_KEY" ]]; then
  echo "bookingKey:   ${BOOKING_KEY:0:64}..."
  echo "priceChange:  $PRICE_CHANGE"
  echo "warnings:     $WARNINGS"
  echo "errors:       $ERRORS"
else
  echo "no bookingKey returned (diagnostics-only envelope)"
  echo "warnings:     $WARNINGS"
  echo "errors:       $ERRORS"
  jq '.applicationResults' "$PRICE_FILE"
fi

# ---------------------------------------------------------------------------
# Step 6 — book-hotel
# ---------------------------------------------------------------------------
if [[ -z "$BOOKING_KEY" ]]; then
  skip 6 "book-hotel" "price-check did not return a bookingKey"
else
  step 6 "book-hotel"

  BOOK_FILE=$(mktemp)
  trap 'cleanup; rm -f "$TMP_ERR" "$SEARCH_FILE" "$CONTENT_FILE" "$AVAIL_FILE" "$DETAILS_FILE" "$PRICE_FILE" "$BOOK_FILE"' EXIT

  # Sabre's published CERT test card (see docs/specifications/create-pnr/
  # sample-request-hotel-gds.json). Not a real PAN. Expiry must be in the
  # future so Sabre doesn't reject on date validation — the Postman
  # sample ships with 3/2022 which has since expired.
  TEST_CARD_NUMBER="4444333322221111"
  TEST_CARD_CODE="VI"
  TEST_CARD_EXPIRY_MONTH="12"
  TEST_CARD_EXPIRY_YEAR="2030"
  TEST_CARD_CVC="123"

  # Agency / billing addresses are derived from Sabre's published
  # sample bodies (docs/specifications/create-pnr/sample-request-hotel-gds.json).
  if ! run_cli $CLI book-hotel "${BASE_URL_FLAG[@]}" \
    --booking-key "$BOOKING_KEY" \
    --first-name "$GIVEN_NAME" --last-name "$SURNAME" --phone "$PHONE" \
    --email "$EMAIL" \
    --card-number "$TEST_CARD_NUMBER" \
    --card-code "$TEST_CARD_CODE" \
    --card-expiry-month "$TEST_CARD_EXPIRY_MONTH" \
    --card-expiry-year "$TEST_CARD_EXPIRY_YEAR" \
    --card-cvc "$TEST_CARD_CVC" \
    --agency-name 'Really Trustworthy Agency' \
    --agency-iata 12345678 \
    --pcc "${SABRE_PCC:-TM61}" \
    --agency-street-number '3150 SABRE DRIVE' \
    --agency-address-line 'SABRE TRAVEL' \
    --agency-city SOUTHLAKE --agency-state TX --agency-country US \
    --agency-postal-code 76092 \
    --billing-address-line '3150 Sabre Drive' \
    --billing-city Southlake --billing-country US --billing-postal-code 76092 \
    --format json >"$BOOK_FILE"; then
    cat "$TMP_ERR" >&2
    fail "book-hotel"
  fi

  PNR_LOCATOR=$(jq -r '.pnrLocator // empty' "$BOOK_FILE")
  AR_STATUS=$(jq -r '.applicationResults.status // empty' "$BOOK_FILE")
  AR_ERRORS=$(jq -r '.applicationResults.errors // [] | length' "$BOOK_FILE")
  AR_WARNINGS=$(jq -r '.applicationResults.warnings // [] | length' "$BOOK_FILE")

  if [[ -n "$PNR_LOCATOR" ]]; then
    echo "pnrLocator:     $PNR_LOCATOR"
    echo "status:         $AR_STATUS"
    echo "errors:         $AR_ERRORS"
    echo "warnings:       $AR_WARNINGS"
  else
    echo "no PNR locator returned (diagnostics-only envelope)"
    echo "status:         $AR_STATUS"
    jq '.applicationResults // empty' "$BOOK_FILE"
  fi
fi

# ---------------------------------------------------------------------------
# Step 7 — get-booking
# ---------------------------------------------------------------------------
if [[ -z "$PNR_LOCATOR" ]]; then
  skip 7 "get-booking (verify hotel)" "no PNR locator to retrieve"
else
  step 7 "get-booking ($PNR_LOCATOR)"

  GET_BOOKING_FILE=$(mktemp)
  trap 'cleanup; rm -f "$TMP_ERR" "$SEARCH_FILE" "$CONTENT_FILE" "$AVAIL_FILE" "$DETAILS_FILE" "$PRICE_FILE" "$BOOK_FILE" "$GET_BOOKING_FILE"' EXIT

  if ! run_cli $CLI get-booking "${BASE_URL_FLAG[@]}" \
      --confirmation-id "$PNR_LOCATOR" \
      --format json >"$GET_BOOKING_FILE"; then
    cat "$TMP_ERR" >&2
    fail "get-booking"
  fi

  GET_BOOKING_HOTEL_NAME=$(jq -r '.hotels[0].hotelName // empty' "$GET_BOOKING_FILE")
  GET_BOOKING_CONFIRMATION=$(jq -r '.hotels[0].confirmationId // empty' "$GET_BOOKING_FILE")
  if [[ -n "$GET_BOOKING_HOTEL_NAME" ]]; then
    echo "hotel name:          $GET_BOOKING_HOTEL_NAME"
    echo "hotel confirmation:  $GET_BOOKING_CONFIRMATION"
  else
    echo "no hotel returned in getBooking response"
    jq '.errors // empty' "$GET_BOOKING_FILE"
  fi
fi

# ---------------------------------------------------------------------------
# Step 8 — cancel-booking
# ---------------------------------------------------------------------------
# Verified in CERT 2026-05-07: booking-management v1 cancelBooking
# accepts a CSL-segment hotel PNR via REST with --cancel-all. Sabre's
# CSL Setup & Guides page lists "Get Reservation — SOAP only" at step 5,
# but that page pre-dates booking-management v1 hotel support.
if [[ -z "$PNR_LOCATOR" ]]; then
  skip 8 "cancel-booking" "no PNR locator to cancel"
elif [[ "$SKIP_CANCEL" == "1" ]]; then
  skip 8 "cancel-booking" "--skip-cancel supplied; leaving PNR live"
else
  step 8 "cancel-booking (cancelAll)"
  CANCEL_FILE=$(mktemp)
  trap 'cleanup; rm -f "$TMP_ERR" "$SEARCH_FILE" "$CONTENT_FILE" "$AVAIL_FILE" "$DETAILS_FILE" "$PRICE_FILE" "$BOOK_FILE" "$GET_BOOKING_FILE" "$CANCEL_FILE"' EXIT
  # Mark cleanup as attempted so the EXIT trap doesn't double-cancel.
  CLEANUP_ATTEMPTED=1
  if ! run_cli $CLI cancel-booking "${BASE_URL_FLAG[@]}" \
      --confirmation-id "$PNR_LOCATOR" --cancel-all \
      --format json >"$CANCEL_FILE"; then
    cat "$TMP_ERR" >&2
    CLEANUP_ATTEMPTED=0  # let the trap take another swing
    fail "cancel-booking"
  fi
  CANCEL_ERRORS=$(jq -r '.errors // [] | length' "$CANCEL_FILE")
  echo "pnrLocator:   $PNR_LOCATOR"
  echo "errors:       $CANCEL_ERRORS"
  if (( CANCEL_ERRORS > 0 )); then
    jq '.errors' "$CANCEL_FILE"
    CLEANUP_ATTEMPTED=0
    fail "cancel-booking"
  fi
fi

echo ""
echo "hotel-e2e complete."
echo "Wrapped steps: 1 (hotel-search), 2 (get-hotel-content), 3 (get-hotel-avail),"
echo "               4 (get-hotel-details), 5 (hotel-price-check), 6 (book-hotel),"
echo "               7 (get-booking), 8 (cancel-booking)."
if [[ -n "$PNR_LOCATOR" && "$SKIP_CANCEL" == "1" ]]; then
  echo ""
  echo "============================================================"
  echo "  LIVE PNR IN CERT (--skip-cancel) — cancel manually: $PNR_LOCATOR"
  echo "============================================================"
fi
